# =============================================================================
# NATIVEFY - Web to Native App Builder
# Production-Quality Codemagic Configuration
# =============================================================================

definitions:
  environment: &environment
    groups:
      - nativefy_credentials
    vars:
      FLUTTER_VERSION: "stable"
      XCODE_VERSION: "latest"
      COCOAPODS_VERSION: "1.14.3"
      NODE_VERSION: "20.10.0"

  cache: &cache
    cache_paths:
      - $HOME/.npm
      - $HOME/.gradle/caches
      - $HOME/Library/Caches/CocoaPods
      - node_modules
      - android/.gradle
      - ios/Pods

  triggering: &triggering
    events:
      - push
      - pull_request
      - tag
    branch_patterns:
      - pattern: 'main'
        include: true
      - pattern: 'release/*'
        include: true
    cancel_previous_builds: true

workflows:
  android-workflow:
    name: "Android Production Build"
    instance_type: linux_x2
    max_build_duration: 60
    <<: *environment
    environment:
      java: 17
      node: 20
      vars:
        APP_NAME: ${APP_NAME}
        SOURCE_URL: ${SOURCE_URL}
        BUNDLE_ID: ${BUNDLE_ID}
        PLATFORM: "android"
    cache:
      <<: *cache
    scripts:
      - name: "Validate build parameters"
        script: |
          echo "NATIVEFY - Android Build Starting"
          echo "App Name: $APP_NAME"
          echo "Source URL: $SOURCE_URL"
          echo "Bundle ID: $BUNDLE_ID"
          if [ -z "$SOURCE_URL" ]; then echo "ERROR: SOURCE_URL is required"; exit 1; fi
          if [ -z "$APP_NAME" ]; then echo "ERROR: APP_NAME is required"; exit 1; fi
          echo "All parameters validated"

      - name: "Install Node.js dependencies"
        script: |
          npm ci --prefer-offline --no-audit

      - name: "Configure app identity"
        script: |
          cat > capacitor.config.ts << EOF
          import { CapacitorConfig } from '@capacitor/cli';
          const config: CapacitorConfig = {
            appId: '${BUNDLE_ID}',
            appName: '${APP_NAME}',
            webDir: 'dist',
            server: { url: '${SOURCE_URL}', cleartext: true, androidScheme: 'https', allowNavigation: ['*'] },
            android: { allowMixedContent: true, captureInput: true, webContentsDebuggingEnabled: false },
            plugins: {
              SplashScreen: { launchShowDuration: 2000, launchAutoHide: true, backgroundColor: '#ffffff', showSpinner: false, splashFullScreen: true, splashImmersive: true },
              StatusBar: { style: 'dark', backgroundColor: '#ffffff' },
              Keyboard: { resize: 'body', resizeOnFullScreen: true }
            }
          };
          export default config;
          EOF

      - name: "Update Android resources"
        script: |
          mkdir -p android/app/src/main/res/values
          cat > android/app/src/main/res/values/strings.xml << EOF
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <string name="app_name">${APP_NAME}</string>
              <string name="title_activity_main">${APP_NAME}</string>
              <string name="package_name">${BUNDLE_ID}</string>
          </resources>
          EOF

      - name: "Build web assets"
        script: npm run build

      - name: "Sync Capacitor"
        script: npx cap sync android --deployment

      - name: "Build Android APK"
        script: |
          cd android
          ./gradlew assembleRelease -Dorg.gradle.jvmargs="-Xmx4g" -Dorg.gradle.parallel=true --no-daemon

      - name: "Build Android AAB"
        script: |
          cd android
          ./gradlew bundleRelease -Dorg.gradle.jvmargs="-Xmx4g" -Dorg.gradle.parallel=true --no-daemon

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab

    publishing:
      scripts:
        - name: "Build complete"
          script: echo "Android build complete for $APP_NAME"

  ios-workflow:
    name: "iOS Production Build"
    instance_type: mac_mini_m2
    max_build_duration: 90
    integrations:
      app_store_connect: nativefy_asc
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: ${BUNDLE_ID}
      xcode: latest
      node: 20
      cocoapods: 1.14.3
      vars:
        APP_NAME: ${APP_NAME}
        SOURCE_URL: ${SOURCE_URL}
        BUNDLE_ID: ${BUNDLE_ID}
        PLATFORM: "ios"
    cache:
      <<: *cache
    scripts:
      - name: "Validate parameters"
        script: |
          echo "NATIVEFY - iOS Build Starting"
          echo "App Name: $APP_NAME"
          echo "Source URL: $SOURCE_URL"
          echo "Bundle ID: $BUNDLE_ID"
          if [ -z "$SOURCE_URL" ]; then echo "ERROR: SOURCE_URL is required"; exit 1; fi
          if [ -z "$APP_NAME" ]; then echo "ERROR: APP_NAME is required"; exit 1; fi

      - name: "Install dependencies"
        script: npm ci --prefer-offline --no-audit

      - name: "Configure app identity"
        script: |
          cat > capacitor.config.ts << EOF
          import { CapacitorConfig } from '@capacitor/cli';
          const config: CapacitorConfig = {
            appId: '${BUNDLE_ID}',
            appName: '${APP_NAME}',
            webDir: 'dist',
            server: { url: '${SOURCE_URL}', cleartext: false, iosScheme: 'https', allowNavigation: ['*'] },
            ios: { contentInset: 'automatic', allowsLinkPreview: true, scrollEnabled: true, preferredContentMode: 'mobile' },
            plugins: {
              SplashScreen: { launchShowDuration: 2000, launchAutoHide: true, backgroundColor: '#ffffff', showSpinner: false, splashFullScreen: true, splashImmersive: true },
              StatusBar: { style: 'dark' },
              Keyboard: { resize: 'body', resizeOnFullScreen: true }
            }
          };
          export default config;
          EOF

      - name: "Build web assets"
        script: npm run build

      - name: "Sync Capacitor"
        script: npx cap sync ios --deployment

      - name: "Install CocoaPods"
        script: |
          cd ios/App
          pod install --repo-update

      - name: "Configure iOS project"
        script: |
          cd ios/App
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName ${APP_NAME}" App/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleName ${APP_NAME}" App/Info.plist

      - name: "Set up code signing"
        script: xcode-project use-profiles

      - name: "Build iOS archive"
        script: |
          cd ios/App
          xcodebuild archive \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates

      - name: "Export IPA"
        script: |
          cd ios/App
          cat > exportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist

    artifacts:
      - ios/App/build/ipa/*.ipa
      - ios/App/build/*.xcarchive

    publishing:
      scripts:
        - name: "Build complete"
          script: echo "iOS build complete for $APP_NAME"
