workflows:
  android-workflow:
    name: Android Build
    instance_type: linux
    max_build_duration: 60
    environment:
      java: 17
      node: 20
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/.gradle/caches
    scripts:
      - name: Validate parameters
        script: |
          if [ -z "$APP_NAME" ] || [ -z "$SOURCE_URL" ] || [ -z "$BUNDLE_ID" ]; then
            echo "Error: Required parameters missing"
            echo "APP_NAME: $APP_NAME"
            echo "SOURCE_URL: $SOURCE_URL"
            echo "BUNDLE_ID: $BUNDLE_ID"
            exit 1
          fi
          echo "Building: $APP_NAME"
          echo "Source: $SOURCE_URL"
          echo "Bundle ID: $BUNDLE_ID"

      - name: Install dependencies
        script: npm ci

      - name: Configure Capacitor
        script: |
          cat > capacitor.config.ts << EOF
          import type { CapacitorConfig } from '@capacitor/cli';
          const config: CapacitorConfig = {
            appId: '$BUNDLE_ID',
            appName: '$APP_NAME',
            webDir: 'dist',
            server: {
              url: '$SOURCE_URL',
              cleartext: true
            }
          };
          export default config;
          EOF

      - name: Update Android resources
        script: |
          sed -i "s/<string name=\"app_name\">.*<\/string>/<string name=\"app_name\">$APP_NAME<\/string>/" android/app/src/main/res/values/strings.xml

      - name: Build web assets
        script: npm run build

      - name: Sync Capacitor
        script: npx cap sync android

      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/apk/**/*.apk
      - android/app/build/outputs/bundle/**/*.aab

  ios-workflow:
    name: iOS Build
    instance_type: mac_mini
    max_build_duration: 90
    integrations:
      app_store_connect: Nativefy ASC
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
      xcode: latest
      node: 20
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/.npm
        - ios/Pods
    scripts:
      - name: Validate parameters
        script: |
          if [ -z "$APP_NAME" ] || [ -z "$SOURCE_URL" ] || [ -z "$BUNDLE_ID" ]; then
            echo "Error: Required parameters missing"
            exit 1
          fi
          echo "Building: $APP_NAME for iOS"

      - name: Install dependencies
        script: npm ci

      - name: Configure Capacitor
        script: |
          cat > capacitor.config.ts << EOF
          import type { CapacitorConfig } from '@capacitor/cli';
          const config: CapacitorConfig = {
            appId: '$BUNDLE_ID',
            appName: '$APP_NAME',
            webDir: 'dist',
            server: {
              url: '$SOURCE_URL',
              cleartext: true
            }
          };
          export default config;
          EOF

      - name: Build web assets
        script: npm run build

      - name: Sync Capacitor
        script: npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Configure iOS project
        script: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName $APP_NAME" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleName $APP_NAME" ios/App/App/Info.plist

      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
